/*

module.exports = {
    Settings: {Spacing: -1, SpaceWidth: 2},
    Characters: {
        A: {Base: 'https://i.imgur.com/NyroibJ.png', Size: Vector2.new(6, 12)},
        B: {Base: 'https://i.imgur.com/F7ywrdS.png', Size: Vector2.new(6, 12)},
        C: {Base: 'https://i.imgur.com/sQCKaS6.png', Size: Vector2.new(5, 12)},
        D: {Base: 'https://i.imgur.com/aWR0T33.png', Size: Vector2.new(6, 12)},
        E: {Base: 'https://i.imgur.com/MDtDsow.png', Size: Vector2.new(6, 12)},
        F: {Base: 'https://i.imgur.com/alYoU9s.png', Size: Vector2.new(5, 12)},
        G: {Base: 'https://i.imgur.com/ZAtUwco.png', Size: Vector2.new(6, 12)},
        H: {Base: 'https://i.imgur.com/bD2J4Wn.png', Size: Vector2.new(6, 12)},
        I: {Base: 'https://i.imgur.com/wxiWtAN.png', Size: Vector2.new(3, 12)},
        J: {Base: 'https://i.imgur.com/4qkiTPb.png', Size: Vector2.new(6, 12)},
        K: {Base: 'https://i.imgur.com/DAyF50c.png', Size: Vector2.new(6, 12)},
        L: {Base: 'https://i.imgur.com/LGFVTgZ.png', Size: Vector2.new(3, 12)},
        M: {Base: 'https://i.imgur.com/rQI7KJm.png', Size: Vector2.new(7, 12)},
        N: {Base: 'https://i.imgur.com/NLA7mol.png', Size: Vector2.new(6, 12)},
        O: {Base: 'https://i.imgur.com/0CS0twf.png', Size: Vector2.new(6, 12)},
        P: {Base: 'https://i.imgur.com/OTKJNYa.png', Size: Vector2.new(6, 12)},
        Q: {Base: 'https://i.imgur.com/wVwEIOF.png', Size: Vector2.new(6, 12)},
        R: {Base: 'https://i.imgur.com/MHBYvip.png', Size: Vector2.new(5, 12)},
        S: {Base: 'https://i.imgur.com/9yFtXuR.png', Size: Vector2.new(6, 12)},
        T: {Base: 'https://i.imgur.com/hv5AkuK.png', Size: Vector2.new(4, 12)},
        U: {Base: 'https://i.imgur.com/cejeise.png', Size: Vector2.new(6, 12)},
        V: {Base: 'https://i.imgur.com/HqRI5zb.png', Size: Vector2.new(7, 12)},
        W: {Base: 'https://i.imgur.com/xzCdt9k.png', Size: Vector2.new(7, 12)},
        X: {Base: 'https://i.imgur.com/LkyrHnh.png', Size: Vector2.new(7, 12)},
        Y: {Base: 'https://i.imgur.com/3dieOEj.png', Size: Vector2.new(6, 12)},
        Z: {Base: 'https://i.imgur.com/a3Z5mXs.png', Size: Vector2.new(5, 12)},

        a: {Base: 'https://i.imgur.com/NyroibJ.png', Size: Vector2.new(6, 12)},
        b: {Base: 'https://i.imgur.com/F7ywrdS.png', Size: Vector2.new(6, 12)},
        c: {Base: 'https://i.imgur.com/sQCKaS6.png', Size: Vector2.new(5, 12)},
        d: {Base: 'https://i.imgur.com/aWR0T33.png', Size: Vector2.new(6, 12)},
        e: {Base: 'https://i.imgur.com/MDtDsow.png', Size: Vector2.new(6, 12)},
        f: {Base: 'https://i.imgur.com/alYoU9s.png', Size: Vector2.new(5, 12)},
        g: {Base: 'https://i.imgur.com/ZAtUwco.png', Size: Vector2.new(6, 12)},
        h: {Base: 'https://i.imgur.com/bD2J4Wn.png', Size: Vector2.new(6, 12)},
        i: {Base: 'https://i.imgur.com/wxiWtAN.png', Size: Vector2.new(3, 12)},
        j: {Base: 'https://i.imgur.com/4qkiTPb.png', Size: Vector2.new(6, 12)},
        k: {Base: 'https://i.imgur.com/DAyF50c.png', Size: Vector2.new(6, 12)},
        l: {Base: 'https://i.imgur.com/LGFVTgZ.png', Size: Vector2.new(3, 12)},
        m: {Base: 'https://i.imgur.com/rQI7KJm.png', Size: Vector2.new(7, 12)},
        n: {Base: 'https://i.imgur.com/NLA7mol.png', Size: Vector2.new(6, 12)},
        o: {Base: 'https://i.imgur.com/0CS0twf.png', Size: Vector2.new(6, 12)},
        p: {Base: 'https://i.imgur.com/OTKJNYa.png', Size: Vector2.new(6, 12)},
        q: {Base: 'https://i.imgur.com/wVwEIOF.png', Size: Vector2.new(6, 12)},
        r: {Base: 'https://i.imgur.com/MHBYvip.png', Size: Vector2.new(5, 12)},
        s: {Base: 'https://i.imgur.com/9yFtXuR.png', Size: Vector2.new(6, 12)},
        t: {Base: 'https://i.imgur.com/hv5AkuK.png', Size: Vector2.new(4, 12)},
        u: {Base: 'https://i.imgur.com/cejeise.png', Size: Vector2.new(6, 12)},
        v: {Base: 'https://i.imgur.com/HqRI5zb.png', Size: Vector2.new(7, 12)},
        w: {Base: 'https://i.imgur.com/xzCdt9k.png', Size: Vector2.new(7, 12)},
        x: {Base: 'https://i.imgur.com/LkyrHnh.png', Size: Vector2.new(7, 12)},
        y: {Base: 'https://i.imgur.com/3dieOEj.png', Size: Vector2.new(6, 12)},
        z: {Base: 'https://i.imgur.com/a3Z5mXs.png', Size: Vector2.new(5, 12)}
    }
}

*/